services:
  riviadev_http_api_postgresql_local:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    env_file:
      - env/local.pg.env
    ports:
      - '5454:5432'
    networks:
      - riviadev_http_api_network_local
    volumes:
      - riviadev_http_api_pg_data_local:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /export/images && minio server /export --console-address=":9001"'
    env_file:
      - env/local.minio.env
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - riviadev_http_api_network_local
    volumes:
      - minio_data_local:/data

  riviadev_http_api_local:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - env/local.app.env
    environment:
      DB_HOST: 'riviadev_http_api_postgresql_local'
      DB_PORT: '5432'
    ports:
      - '3000:3000'
    depends_on:
      - minio
      - riviadev_http_api_postgresql_local
    networks:
      - riviadev_http_api_network_local

volumes:
  riviadev_http_api_pg_data_local:
  minio_data_local:

networks:
  riviadev_http_api_network_local:
    driver: bridge
