services:
  riviadev_http_api_postgresql_local:
    build: docker/postgres/.
    env_file:
      - env/local.pg.env
    ports:
      - '5454:5432'
    networks:
      - riviadev_http_api_network_local
    volumes:
      - riviadev_http_api_pg_data_local:/var/lib/postgresql/data

volumes:
  riviadev_http_api_pg_data_local:

networks:
  riviadev_http_api_network_local:
    driver: bridge
