services:
  riviadev_http_api_postgresql_local:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    env_file:
      - env/local.pg.env
    ports:
      - '5454:5432'
    networks:
      - riviadev_http_api_network_local
    volumes:
      - riviadev_http_api_pg_data_local:/var/lib/postgresql/data

  riviadev_http_api_local:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - env/local.app.env
    environment:
      DB_HOST: 'riviadev_http_api_postgresql_local'
      DB_PORT: '5432'
    ports:
      - '3000:3000'
    networks:
      - riviadev_http_api_network_local

volumes:
  riviadev_http_api_pg_data_local:

networks:
  riviadev_http_api_network_local:
    driver: bridge
