services:
  postgresql_local:
    build: docker/postgres/.
    env_file:
      - env/local.pg.env
    ports:
      - "5432:5432"
    networks:
      - riviadev_network_local
    volumes:
      - riviadev_data_local:/var/lib/postgresql/data

volumes:
  riviadev_data_local:

networks:
  riviadev_network_local:
    driver: bridge
